// Shell commands the gate must hold or pass; shared by the classifier and the hook prefilter tests.
export const HELD_SHELL_COMMANDS: readonly string[] = [
  'git push --force-with-lease origin custom',
  'git push -f origin main',
  'git push --force',
  'git push origin +feature/x',
  'git push origin :feature/x',
  'git push --delete origin feature/x',
  'git push -d origin v1.4.2',
  'git push --mirror backup',
  'git push --prune origin',
  'git push origin feature/x && git push --force origin main',
  'git -c core.hooksPath=/dev/null push --force',
  'bash -c "git push --force origin main"',
  'git send-email --to=team@example.com 0001.patch',
  'gh repo delete o/r --yes',
  'gh release delete v1.2',
  'gh api -X DELETE repos/o/r/git/refs/heads/x',
  'glab mr delete 7',
  'glab api --method DELETE projects/1/issues/2',
  'curl -X DELETE https://api.clickup.com/api/v2/task/1',
  'curl --request DELETE "https://api.example.com/items/9"',
  'curl -X POST https://slack.com/api/chat.postMessage -d text=hi',
  "curl -X POST -H 'Content-type: application/json' -d '{}' https://hooks.slack.com/services/T/B/x",
  'curl -s "https://api.telegram.org/bot$TOKEN/sendMessage" -d chat_id=1 -d text=hi',
  'curl -X POST https://desk.zoho.com/api/v1/tickets/1/sendReply -d @reply.json',
  'curl -X POST https://graph.microsoft.com/v1.0/me/sendMail --json @mail.json',
  'curl -X PUT -d \'{"description":"new"}\' https://api.clickup.com/api/v2/task/1',
  'curl -X PUT -d \'{"name":"Renamed"}\' https://api.clickup.com/api/v2/task/1',
  'curl -X PUT -d "$BODY" https://api.clickup.com/api/v2/task/1',
  'curl -X POST http://127.0.0.1:3000/x; curl -X DELETE https://n8n.example.com/webhook/y',
  'wget --method=DELETE https://example.com/item/1',
  'http DELETE https://example.com/api/item/1',
  "python3 - <<'PY'\nimport requests\nrequests.post('https://hooks.slack.com/services/x', json={})\nPY",
  "python3 - <<'PY'\nimport requests\nrequests.delete('https://api.example.com/items/1')\nPY",
  "node -e \"fetch('https://api.example.com/x', { method: 'DELETE' })\"",
  'ssh myserver "rm -rf /srv/app/data"',
  "ssh myserver 'docker volume rm app_db'",
  'psql "$DATABASE_URL" -c "DROP TABLE orders"',
  'psql "$DATABASE_URL" -c "DELETE FROM sessions"',
  'sh -c \'ssh myserver "TRUNCATE events"\'',
  'kubectl delete deploy api',
  'terraform destroy -auto-approve',
  'aws s3 rm s3://bucket/key',
  'npm unpublish pkg@1.0.0'
]

export const PASSED_SHELL_COMMANDS: readonly string[] = [
  'git status',
  'git log --oneline -5',
  'git commit -m "describe the gate"',
  'git pull --rebase',
  'git push',
  'git push origin main',
  'git push -u origin feature/x',
  'git push origin feature/x:master',
  'git push --tags origin',
  'git push -q origin fix-login:fix-login',
  'git fetch origin',
  'gh pr create --title x --body y',
  'gh pr merge 12 --squash',
  'gh issue comment 5 --body hi',
  'gh api repos/o/r/issues/1/comments -f body=hi',
  'gh pr view 12',
  'glab mr merge 7',
  'glab mr note 7 -m "ok"',
  'ssh myserver "docker ps"',
  'ssh myserver "docker compose up -d --build"',
  'scp file myserver:/tmp/',
  'rsync -az dist/ myserver:/srv/app/',
  'ssh-keygen -lf key.pub',
  'curl -sS https://example.com',
  'curl -d @body.json "$WEBHOOK_URL"',
  'curl -X POST https://n8n.example.com/webhook/y -d x',
  "curl -sS -H 'Authorization: x' --data-raw '{}' https://api.clickup.com/api/v2/task/1/comment",
  'curl https://api.clickup.com/api/v2/task/1 \\\n  -X PUT --json \'{"status":"check"}\'',
  'curl -X POST -d @comment.json https://api.clickup.com/api/v2/task/1/comment',
  "curl -X POST -d '{}' https://api.clickup.com/api/v2/list/9/task",
  'curl -X DELETE http://127.0.0.1:8080/hook',
  'wget --post-data "a=1" https://example.com/form',
  'http POST https://example.com/api name=x',
  "node -e \"fetch('https://api.example.com', { method: 'POST' })\"",
  'psql "$DATABASE_URL" -c "select count(*) from orders"',
  'orca-plus linear comment add ABC-1 --body hi',
  'orca artifacts share ./page.html',
  'pnpm publish --access public',
  'docker push ghcr.io/x/y:1',
  'kubectl apply -f deploy.yaml',
  'bash scripts/orca-plus-ship.sh --no-build',
  'sed -n 1,28p scripts/orca-plus-ship.sh',
  'pnpm test',
  'rm -rf node_modules'
]
